spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

spring.datasource.url=jdbc:postgresql://db_learning_krge_user:400Vbrxx0h9M6wtteUn1e2ZhtrESa5PO@dpg-d4ctn9n5r7bs73al649g-a.frankfurt-postgres.render.com:5432/db_learning_krge
spring.datasource.username=db_learning_krge_user
spring.datasource.password=400Vbrxx0h9M6wtteUn1e2ZhtrESa5PO
spring.profiles.active=${SPRING_PROFILE:default}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}
